Repository jobinmatt/SYSC4806_MiniShopify, pull requests merged in 2020-04, with the labels that each got.

#94 Fixed several issues with CreateShop
  frontend/src/App.vue
  frontend/src/components/EditItem.vue
  frontend/src/components/ShopItem.vue
  frontend/src/constants/constants.js
  frontend/src/main.js
  frontend/src/pages/CreateShopPage.vue
  frontend/src/pages/Login.vue
  frontend/src/pages/MerchantShops.vue
  frontend/src/pages/ShopPage.vue
  frontend/src/pages/SignUp.vue
  frontend/test/unit/specs/Login.spec.js
  frontend/test/unit/specs/Signup.spec.js
Labels: bug fix, enhancement

#97 Added Cart UI
  frontend/src/App.vue
  frontend/src/components/CartItem.vue
  frontend/src/components/EditItem.vue
  frontend/src/components/ProductItem.vue
  frontend/src/components/ShopItem.vue
  frontend/src/main.js
  frontend/src/pages/AllShopsPage.vue
  frontend/src/pages/Cart.vue
  frontend/src/pages/CartPage.vue
  frontend/src/pages/CreateShopPage.vue
  frontend/src/pages/Login.vue
  frontend/src/pages/MerchantShops.vue
  frontend/src/pages/ShopPage.vue
  frontend/src/pages/SignUp.vue
  frontend/test/unit/specs/Login.spec.js
  frontend/test/unit/specs/Signup.spec.js
Labels: enhancement, story

#101 #96 #98
  backend/src/main/java/springboot/controller/CartController.java
  backend/src/main/java/springboot/model/Cart.java
  backend/src/main/java/springboot/model/CartItem.java
  backend/src/main/java/springboot/model/Owner.java
Labels: bug fix

#102 UI updates
  backend/src/main/java/springboot/constants/JWTConstants.java
  frontend/src/App.vue
  frontend/src/components/CartItem.vue
  frontend/src/components/ShopItem.vue
  frontend/src/main.js
  frontend/src/pages/AllShopsPage.vue
  frontend/src/pages/CartPage.vue
  frontend/src/pages/CreateShopPage.vue
  frontend/src/pages/Dashboard.vue
  frontend/src/pages/Login.vue
  frontend/src/pages/Search.vue
  frontend/src/pages/ShopPage.vue
  frontend/src/pages/SignUp.vue
Labels: bug fix, enhancement, story
