Repository jobinmatt/SYSC4806_MiniShopify, pull requests merged in 2020-03, with the labels that each got.

#60 Created navbar, login and signup
  frontend/config/index.js
  frontend/package.json
  frontend/pom.xml
  frontend/src/App.vue
  frontend/src/components/HelloWorld.vue
  frontend/src/pages/Login.vue
  frontend/src/pages/SignUp.vue
  frontend/test/e2e/specs/signup_test.js
  frontend/test/unit/jest.conf.js
  frontend/test/unit/specs/HelloWorld.spec.js
  frontend/test/unit/specs/Login.spec.js
  frontend/test/unit/specs/Signup.spec.js
Labels: story

#63 Added CreateStorePage
  .gitignore
  data/MiniShopify.mv.db
  frontend/src/App.vue
  frontend/src/components/EditItem.vue
  frontend/src/main.js
  frontend/src/pages/CreateShopPage.vue
Labels: enhancement, good first issue, story

#68 Hooked up Signup page
  backend/pom.xml
  backend/src/main/java/springboot/Application.java
  backend/src/main/java/springboot/config/WebSecurity.java
  backend/src/main/java/springboot/constants/JWTConstants.java
  backend/src/main/java/springboot/controller/OwnerController.java
  backend/src/main/java/springboot/controller/ShopController.java
  backend/src/main/java/springboot/filters/JWTAuthenticationFilter.java
  backend/src/main/java/springboot/filters/JWTAuthorizationFilter.java
  backend/src/main/java/springboot/model/Owner.java
  backend/src/main/java/springboot/services/OwnerDetailsServiceImpl.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/constants/constants.js
  frontend/src/pages/Login.vue
  frontend/src/pages/SignUp.vue
Labels: story

#78 Update README.md
  README.md
Labels: documentation

#77 create shop page is now functional
  frontend/src/App.vue
  frontend/src/components/EditItem.vue
  frontend/src/constants/constants.js
  frontend/src/pages/CreateShopPage.vue
  frontend/src/pages/Login.vue
  frontend/src/pages/SignUp.vue
Labels: story

#82 fixed #81, and fixed 98% of ESLint errors.
  backend/src/main/java/springboot/config/WebSecurity.java
  backend/src/main/java/springboot/constants/JWTConstants.java
  backend/src/main/java/springboot/controller/OwnerController.java
  backend/src/main/java/springboot/controller/ShopController.java
  backend/src/main/java/springboot/filters/JWTAuthenticationFilter.java
  backend/src/main/java/springboot/filters/JWTAuthorizationFilter.java
  frontend/src/App.vue
  frontend/src/components/EditItem.vue
  frontend/src/constants/constants.js
  frontend/src/main.js
  frontend/src/pages/CreateShopPage.vue
  frontend/src/pages/Dashboard.vue
  frontend/src/pages/Login.vue
  frontend/src/pages/SignUp.vue
Labels: bug

#87 New intergration tests
  backend/pom.xml
  backend/src/main/java/springboot/Repository/ItemRepository.java
  backend/src/main/java/springboot/Repository/OwnerRepository.java
  backend/src/main/java/springboot/Repository/ShopRepository.java
  backend/src/main/java/springboot/config/WebSecurity.java
  backend/src/main/java/springboot/controller/OwnerController.java
  backend/src/main/java/springboot/controller/ShopController.java
  backend/src/main/java/springboot/filters/JWTAuthenticationFilter.java
  backend/src/main/java/springboot/model/Cart.java
  backend/src/main/java/springboot/model/Item.java
  backend/src/main/java/springboot/model/Owner.java
  backend/src/main/java/springboot/model/Shop.java
  backend/src/test/java/ShopControllerTests.java
Labels: story, urgent
